# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpapi', '0003_auto_20170522_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='watch_start',
            field=models.DateTimeField(),
        ),
    ]
