# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpapi', '0005_auto_20170522_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='count_user',
            new_name='count_users',
        ),
    ]
